---
abstract: 'simple, non-Moose interface to the Stripe API'
author:
  - 'Andy Beverley <andy@andybev.com>'
  - 'Grant Street Group <developers@grantstreet.com>'
  - 'David F. Houghton <dfhoughton@gmail.com>'
build_requires:
  DateTime: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Exception: '0'
  Test::More: '0'
  autodie: '0'
  blib: '1.01'
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: v5.10.0
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Stripe-Simple
no_index: {}
requires:
  Devel::StackTrace: '0'
  Exporter: '0'
  HTTP::Request::Common: '0'
  JSON: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  Scalar::Util: '0'
  URI::Escape: '0'
  constant: '0'
  overload: '0'
  parent: '0'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/infosaas/Net-Stripe-Simple.git
version: '0.004'
x_serialization_backend: 'YAML::Tiny version 1.69'
